name: Test library

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version:
          - 18
          - 20
          - 22
          - 23

    env:
      NODE_OPTIONS: '--dns-result-order=ipv4first'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: npm ci
    - run: npm test

  startup-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 22

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - run: |
        echo "Branch: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
    - name: prepare
      run: |
        npm install ../
        touch test.md
      working-directory: ./link_check
    - run: npx markdown-link-check link_check/test.md
      working-directory: ./link_check
